name: 'zap_testing'
on:
  workflow_dispatch:
  push:
    branches:
      - zap
  pull_request:
    branches: [gf-ecs]
defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

concurrency: ${{ github.head_ref || github.ref_name || github.run_id }}
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: zap
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.zaproxy.org/'
          gen_file: 'owasp/zap-baseline.conf'
          cmd_options: '-a'
