name: 'Deployment'
on:
  workflow_dispatch:
  push:
    branches:
      - ecs-fargate-poc
  pull_request:
    branches: [ecs-fargate-poc]
defaults:
  run:
    shell: bash
concurrency: ${{ github.head_ref || github.ref_name || github.run_id }}
jobs:
  terraform:
    name: ${{matrix.runner}} - stage
    runs-on: ['${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: stage
            runner: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-region: us-east-1
      #     #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     #aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the web image to Amazon ECR
        id: build-web-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_URL }}
          ECR_REPOSITORY: ${{ secrets.WEB_ECR_REPOSITORY }}
        run: |
          # Build a docker container and push it to ECR
          export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker build --quiet -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f web/Dockerfile .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          export WEB_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::${WEB_IMAGE}"

      - name: Build, tag, and push the api image to Amazon ECR
        id: build-api-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_URL }}
          ECR_REPOSITORY: ${{ secrets.API_ECR_REPOSITORY }}
        run: |
          # Build a docker container and push it to ECR
          export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker build --quiet -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f api/Dockerfile .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          export API_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::${API_IMAGE}"

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        working-directory: terraform/greenfiel/ecs
        run: |
          rm -rf .terraform
          terraform init -backend-config=stage/backend.tfvars -upgrade=true -no-color -input=false
      - name: Terraform Plan
        id: plan
        working-directory: terraform/greenfiel/ecs
        run: |
          terraform plan -input=false -var-file=stage/terraform.tfvars -var "web_image=$WEB_IMAGE" -var "api_image=$API_IMAGE" -no-color
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}
      - name: Terraform Apply
        if: github.ref == 'refs/heads/ecs-fargate-poc'
        id: apply
        working-directory: terraform/greenfiel/ecs
        run: |
          terraform apply -auto-approve -input=false -var-file=stage/terraform.tfvars -var "web_image=$WEB_IMAGE"  -var "api_image=$API_IMAGE"
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}
      - name: Terraform destroy
        if: github.ref == 'refs/heads/destroy'
        id: destroy
        working-directory: terraform/greenfiel/ecs
        run: |
          terraform destroy -auto-approve -input=false -var-file=stage/terraform.tfvars
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}
