name: 'zap_testing'
on:
  workflow_dispatch:
  push:
    branches:
      - zap
  pull_request:
    branches: [gf-ecs]
defaults:
  run:
    shell: bash

concurrency: ${{ github.head_ref || github.ref_name || github.run_id }}
jobs:
  zap_scan:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: zap

      - name: zap scan with docker image
        continue-on-error: true
        run: |
          ls
          docker run -v $(pwd):/zap/wrk/:rw --user root -t owasp/zap2docker-stable zap-baseline.py -t https://www.zaproxy.org/ -c owasp/rules.tsv -g gen.conf -I

      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.3.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: 'https://www.zaproxy.org/'
      #     rules_file_name: 'rules.tsv'
      #     cmd_options: '-I'
