name: 'zap_testing'
on:
  workflow_dispatch:
  push:
    branches:
      - zap
  pull_request:
    branches: [gf-ecs]
defaults:
  run:
    shell: bash

concurrency: ${{ github.head_ref || github.ref_name || github.run_id }}
jobs:
  zap_scan:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: zap
      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-tok
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.zaproxy.org/'
          rules_file_name: 'owasp/rules.tsv'
          cmd_options: '-I'
